services:
  mysql-db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: code1!
      MYSQL_DATABASE: code-db
      MYSQL_USER: code-user
      MYSQL_PASSWORD: code1!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: